// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgvddfooymfwiabtpify.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndmRkZm9veW1md2lhYnRwaWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODQ4NTgsImV4cCI6MjA2MjA2MDg1OH0.nAk06ecJE2xEyFQoRSqlEvlcVHa0EOW_lbvBQetmE5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);