// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gddvioovcwdkqxgfnyuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZHZpb292Y3dka3F4Z2ZueXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDgzNzAsImV4cCI6MjA2MjE4NDM3MH0.zqMbHG9hOac1f5nzhohZGHR_2o2290UAO4V2K2Bo54I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);